### ISSUE TITLE
Update Google form to be 2025

### ISSUE THREAD

**Issue by npomponio** [MidAtlanticDreamin/MidAtlanticDreamin.github.io#19]
Not sure who owns the form, but please update from 2024 to 2025

https://docs.google.com/forms/d/e/1FAIpQLSduO22OA2qBt1h9Vq17Jchi-qAmzmafUswyRMQ5CuJCcy-JhQ/viewform

**Comment by catalandres** [comment]
@npomponio  — This fell under the purview of the Sponsorships team.
My best bet is that Liz was in charge of it.
From the website's perspective, we can only replace this link with a link to a new form, versioned for 2025.

**Comment by judisohn** [comment]
I pointed @npomponio to last year's form that can be cloned from last year and then I can do a PR to update the link when that's ready.

**Comment by npomponio** [comment]
@catalandres @judisohn form is updated - https://forms.gle/bmXk5tdsf4LRJ7Pr6
can we replace please?

**Comment by npomponio** [comment]
@catalandres Judy needs help completing this action. Can we sync up on this please?
